apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: cilium-monitoring
spec:
  selector:
    app: metrics-app  # Corrected selector key
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

