version: '3'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    container_name: filebeat
    user: root
    network_mode: host
    volumes:
      #- /home/ubuntu/fyp/bcc_data:/data
      - /home/ubuntu/fyp/phase2/gadget/data:/data
      - /home/ubuntu/fyp/phase2/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
    command: filebeat -e --strict.perms=false

