apiVersion: v1
kind: Pod
metadata:
  name: bcc-pod
  namespace: cilium-monitoring 
spec:
  containers:
  - name: bcc-container
    image: abwqr/bcc
    command: ["/bin/bash"]
    args: ["-c", "apt-get update && apt-get install linux-headers-$(uname -r) -y && sleep infinity"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: lib-modules
      mountPath: /lib/modules/
      readOnly: false 
    - name: sys
      mountPath: /sys/
      readOnly: false 
    - name: usr-src
      mountPath: /usr/src/
      readOnly: false 
    - name: data
      mountPath: /data
          
     
  volumes:
  - name: lib-modules
    hostPath:
      path: /lib/modules/
  - name: sys
    hostPath:
      path: /sys/
  - name: usr-src
    hostPath:
      path: /usr/src/
  - name: data
    persistentVolumeClaim:
      claimName: pvc-dynamic
