apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /home/ubuntu/fyp/phase2/k8s/
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc1
  namespace: cilium-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: shared-pvc1
