# deployment_and_service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: cilium-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: abwqr/doctors:4819d7

---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: cilium-monitoring
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: cilium-monitoring
spec:
  containers:
  - name: busybox
    image: abwqr/doctors:4819d7
    command:
      - sleep
      - "3600"

