---
apiVersion: v1
kind: Namespace
metadata:
  name: oomkill-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: oomkill-demo
spec:
  containers:
  - name: test-container
    image: busybox
    resources:
      limits:
        memory: "64Mi"
    command: ["sleep", "inf"]
